/// <reference types="node" />
// =====================================================================
// erp_print_format_probe.ts
// Which print format does each document actually render with, and why?
//
// READ-ONLY. Nothing here writes anything.
//
//   npx tsx src/db/erp_print_format_probe.ts
//
// Written for one symptom: a QUOTATION previewing as a document titled
// "Purchase Order". Only three things can cause that, and this checks all
// three rather than guessing:
//
//   1. ERP_QUOTE_PRINT_FORMAT points at the wrong format.
//   2. The Quotation doctype's default_print_format does.
//   3. Neither is set, so fetchQuotationPdf() falls back to the most
//      recently MODIFIED enabled format for Quotation — and something
//      re-pointed a format at the Quotation doctype, or edited one.
//
// It reproduces quotePrintFormat()'s resolution EXACTLY, in the same
// order, and says which branch won. Then it fingerprints every candidate
// by what its HTML actually says, because a format's name tells you
// nothing about what it prints.
// =====================================================================

import 'dotenv/config';

const BASE = process.env.ERPNEXT_URL?.replace(/\/+$/, '');
const KEY = process.env.ERPNEXT_API_KEY;
const SECRET = process.env.ERPNEXT_API_SECRET;

const PO_DOCTYPE = process.env.ERP_PO_DOCTYPE ?? 'SGT Dealer PO';
const PO_FORMAT_ENV = process.env.ERP_PO_PRINT_FORMAT?.trim() ?? '';
const QUOTE_FORMAT_ENV = process.env.ERP_QUOTE_PRINT_FORMAT?.trim() ?? '';

if (!BASE || !KEY || !SECRET) {
  console.error('✗ ERPNEXT_URL / ERPNEXT_API_KEY / ERPNEXT_API_SECRET must be set');
  process.exit(1);
}
const headers = {
  Authorization: `token ${KEY}:${SECRET}`,
  Accept: 'application/json',
  'Content-Type': 'application/json',
};

async function call(path: string) {
  const res = await fetch(`${BASE}${path}`, { headers });
  const text = await res.text();
  let json: any = null;
  try { json = JSON.parse(text); } catch { /* non-JSON */ }
  return { ok: res.ok, status: res.status, json, text };
}

async function getDoc(doctype: string, name: string) {
  const r = await call(`/api/resource/${encodeURIComponent(doctype)}/${encodeURIComponent(name)}`);
  return r.ok ? r.json?.data ?? null : null;
}

/** What a format's HTML actually says. Names lie; this does not. */
function fingerprint(html: string): string {
  const marks: string[] = [];
  const has = (needle: string, label: string) => {
    if (html.toLowerCase().includes(needle.toLowerCase())) marks.push(label);
  };
  has('Techno-Commercial Offer', 'title:Techno-Commercial Offer');
  has('Purchase Order', 'says:Purchase Order');
  has('Quote Generated by', 'block:Quote Generated by');
  has('PO Raised By', 'block:PO Raised By');
  has('Against Quotation', 'row:Against Quotation');
  has('Equipment Specification', 'block:Equipment Specification');
  return marks.length ? marks.join(', ') : '(no known markers)';
}

async function formatsFor(docType: string) {
  const r = await call(
    `/api/resource/${encodeURIComponent('Print Format')}` +
    `?filters=${encodeURIComponent(JSON.stringify([['doc_type', '=', docType]]))}` +
    `&fields=${encodeURIComponent(JSON.stringify(
      ['name', 'doc_type', 'disabled', 'custom_format', 'print_format_type', 'modified']))}` +
    `&limit_page_length=50&order_by=modified desc`);
  return (r.json?.data ?? []) as any[];
}

/**
 * quotePrintFormat() from services/erpQuotation.ts, reproduced.
 *
 * Deliberately a copy rather than an import: this must report what the
 * RUNNING server would choose, including the env it is reading, and
 * importing the real one would hide the branch that won.
 */
async function resolveQuotationFormat(): Promise<{ name: string | null; via: string }> {
  if (QUOTE_FORMAT_ENV) {
    return { name: QUOTE_FORMAT_ENV, via: 'ERP_QUOTE_PRINT_FORMAT (pinned in .env)' };
  }
  const dt = await getDoc('DocType', 'Quotation');
  if (dt?.default_print_format) {
    return {
      name: String(dt.default_print_format),
      via: 'the Quotation doctype\'s default_print_format',
    };
  }
  const rows = await formatsFor('Quotation');
  const live = rows.filter(f => !f.disabled);
  return live.length
    ? {
        name: String(live[0].name),
        via: 'FALLBACK — the most recently MODIFIED enabled Quotation format',
      }
    : { name: null, via: 'nothing found; ERPNext renders its standard format' };
}

async function main() {
  console.log(`▶ print format probe — ${BASE}\n`);

  console.log('1. Environment');
  console.log(`   ERP_QUOTE_PRINT_FORMAT = ${QUOTE_FORMAT_ENV || '(unset)'}`);
  console.log(`   ERP_PO_PRINT_FORMAT    = ${PO_FORMAT_ENV || '(unset)'}`);
  console.log(`   ERP_PO_DOCTYPE         = ${PO_DOCTYPE}`);
  if (QUOTE_FORMAT_ENV && PO_FORMAT_ENV && QUOTE_FORMAT_ENV === PO_FORMAT_ENV) {
    console.log('   ✗ THESE ARE THE SAME. One format cannot be both documents —');
    console.log('     whichever layout it holds is what BOTH will print.');
  }

  console.log('\n2. What a QUOTATION renders with');
  const q = await resolveQuotationFormat();
  console.log(`   → ${q.name ?? '(none)'}`);
  console.log(`     via ${q.via}`);
  if (q.name) {
    const fmt = await getDoc('Print Format', q.name);
    if (!fmt) {
      console.log('     ✗ that format does not exist — ERPNext will fall back or fail.');
    } else {
      console.log(`     doc_type=${fmt.doc_type}  disabled=${fmt.disabled ?? 0}  ` +
                  `custom=${fmt.custom_format ?? 0}  modified=${fmt.modified}`);
      console.log(`     contains: ${fingerprint(String(fmt.html ?? ''))}`);
      if (String(fmt.doc_type) !== 'Quotation') {
        console.log(`     ✗ IT BELONGS TO "${fmt.doc_type}", NOT Quotation.`);
        console.log('       Something rebound it. That is the bug: quotations are being');
        console.log('       rendered through another doctype\'s layout.');
      }
      if (String(fmt.html ?? '').includes('Purchase Order')) {
        console.log('     ✗ ITS HTML SAYS "Purchase Order" — this is what you are seeing.');
      }
    }
  }

  console.log('\n3. What a DEALER PO renders with');
  const poName = PO_FORMAT_ENV ||
    (await getDoc('DocType', PO_DOCTYPE))?.default_print_format || '';
  console.log(`   → ${poName || '(none)'}`);
  if (poName) {
    const fmt = await getDoc('Print Format', poName);
    if (!fmt) console.log('     ✗ that format does not exist.');
    else {
      console.log(`     doc_type=${fmt.doc_type}  disabled=${fmt.disabled ?? 0}  ` +
                  `modified=${fmt.modified}`);
      console.log(`     contains: ${fingerprint(String(fmt.html ?? ''))}`);
      if (String(fmt.doc_type) !== PO_DOCTYPE) {
        console.log(`     ✗ IT BELONGS TO "${fmt.doc_type}", NOT ${PO_DOCTYPE}.`);
      }
    }
  }

  console.log('\n4. Every Print Format on either doctype');
  for (const dt of ['Quotation', PO_DOCTYPE]) {
    const rows = await formatsFor(dt);
    console.log(`   ${dt}: ${rows.length} format(s)`);
    for (const f of rows) {
      const full = await getDoc('Print Format', f.name);
      console.log(`     · ${f.name}`);
      console.log(`         disabled=${f.disabled ?? 0} custom=${f.custom_format ?? 0} ` +
                  `type=${f.print_format_type ?? '—'} modified=${f.modified}`);
      console.log(`         contains: ${fingerprint(String(full?.html ?? ''))}`);
    }
  }

  console.log('\n5. Reading this');
  console.log('   The quotation should resolve to a format whose fingerprint includes');
  console.log('   "title:Techno-Commercial Offer" and "block:Quote Generated by".');
  console.log('   The PO should resolve to one with "block:PO Raised By".');
  console.log('   A format containing BOTH "Quote Generated by" and "Purchase Order" is');
  console.log('   your quotation layout with its title edited — fix the title in ERPNext,');
  console.log('   and give the PO a format of its own.');
}

main().catch(e => { console.error(e); process.exit(1); });
