// =============================================================================
// VAULT PHASE 0/1 · Migration 02 · poc_service module
// -----------------------------------------------------------------------------
// Run once on the VPS:  cd sgt-hydroedge-server && npx tsx src/db/migrate_vault_02_poc.ts
//
// Structured POC records + readings (test data / fuel / run-hours / emissions),
// observations (incl. customer comments / objections / appreciation), and
// issues + corrective actions.
//
// Human-readable display_ids are generated by a DEFAULT off a sequence
// (POC-1001, ISS-1001) so inserts don't need app-side id logic. This mirrors
// your lead_id_seq idea but wires it straight into the column DEFAULT.
//
// Refs: account_id -> real FK to the shared spine. site_id / lead_id -> loose
// (cross-module). poc_reading/observation/issue -> real FK to poc (same schema).
// =============================================================================
import 'dotenv/config'
import { pool } from './pool.js'

async function main() {
  const client = await pool.connect()
  try {
    await client.query('BEGIN')

    await client.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`)
    await client.query(`CREATE SCHEMA IF NOT EXISTS poc_service;`)

    await client.query(`CREATE SEQUENCE IF NOT EXISTS poc_service.poc_id_seq   START 1001 INCREMENT 1;`)
    await client.query(`CREATE SEQUENCE IF NOT EXISTS poc_service.issue_id_seq START 1001 INCREMENT 1;`)

    // POC record --------------------------------------------------------------
    await client.query(`
      CREATE TABLE IF NOT EXISTS poc_service.poc (
        id                   UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        display_id           TEXT UNIQUE NOT NULL
                               DEFAULT ('POC-' || nextval('poc_service.poc_id_seq')),
        account_id           UUID NOT NULL REFERENCES lead_service.accounts(id),
        site_id              UUID,                   -- loose ref to customer_service.customer_site
        lead_id              UUID,                   -- loose ref to lead_service.leads (originating opportunity)

        product              TEXT NOT NULL,          -- GreenDrive | GreenX | HHOx | GreenMarine | GreenEdge | GreenVision
        application          TEXT,                   -- vehicle | dg | marine | boiler | kiln | furnace | industrial
        equipment_make       TEXT,
        equipment_model      TEXT,
        rating_value         NUMERIC,                -- e.g. 500 (kVA), 10 (TPH), tonnage
        rating_unit          TEXT,                   -- kVA | TPH | HP | tonne | ...
        fuel_type            TEXT,                   -- diesel | coal | furnace_oil | gas | ...
        spec                 JSONB DEFAULT '{}',     -- engine make/model + any extra equipment details

        baseline_from        DATE,
        baseline_to          DATE,
        trial_from           DATE,
        trial_to             DATE,
        start_date           DATE,
        end_date             DATE,

        status               TEXT NOT NULL DEFAULT 'planned', -- planned | installing | monitoring | completed | aborted
        savings_pct          NUMERIC,                -- for AI filtering ("savings above 10%")
        final_result         TEXT,
        recommended_next_step TEXT,
        sgt_comments         TEXT,
        customer_comments    TEXT,

        owner_id             TEXT,
        owner_name           TEXT,
        metadata             JSONB DEFAULT '{}',
        created_by           TEXT,
        created_by_name      TEXT,
        created_at           TIMESTAMPTZ DEFAULT NOW(),
        updated_at           TIMESTAMPTZ DEFAULT NOW(),
        deleted_at           TIMESTAMPTZ
      );
    `)
    await client.query(`CREATE INDEX IF NOT EXISTS idx_poc_account     ON poc_service.poc(account_id);`)
    await client.query(`CREATE INDEX IF NOT EXISTS idx_poc_status      ON poc_service.poc(status);`)
    await client.query(`CREATE INDEX IF NOT EXISTS idx_poc_product_app ON poc_service.poc(product, application);`)
    await client.query(`CREATE INDEX IF NOT EXISTS idx_poc_savings     ON poc_service.poc(savings_pct);`)

    // Readings: test data, fuel logs, run-hours, emission readings ------------
    await client.query(`
      CREATE TABLE IF NOT EXISTS poc_service.poc_reading (
        id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        poc_id           UUID NOT NULL REFERENCES poc_service.poc(id),
        reading_type     TEXT NOT NULL,             -- fuel | run_hours | emission | baseline | trial | meter | other
        reading_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        numeric_value    NUMERIC,
        unit             TEXT,                       -- litres | hours | ppm | kg | ...
        label            TEXT,
        notes            TEXT,
        source           TEXT DEFAULT 'manual',      -- manual | mobile | whatsapp | greenvision
        captured_by      TEXT,
        captured_by_name TEXT,
        metadata         JSONB DEFAULT '{}',
        created_at       TIMESTAMPTZ DEFAULT NOW()
      );
    `)
    await client.query(`CREATE INDEX IF NOT EXISTS idx_reading_poc  ON poc_service.poc_reading(poc_id, reading_at DESC);`)
    await client.query(`CREATE INDEX IF NOT EXISTS idx_reading_type ON poc_service.poc_reading(reading_type);`)

    // Observations: SGT notes, customer comments, objections, appreciation ----
    await client.query(`
      CREATE TABLE IF NOT EXISTS poc_service.poc_observation (
        id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        poc_id       UUID NOT NULL REFERENCES poc_service.poc(id),
        observed_at  TIMESTAMPTZ DEFAULT NOW(),
        author_side  TEXT DEFAULT 'sgt',            -- sgt | customer
        author_id    TEXT,
        author_name  TEXT,
        category     TEXT,                           -- observation | customer_comment | appreciation | objection | risk
        body         TEXT NOT NULL,
        metadata     JSONB DEFAULT '{}',
        created_at   TIMESTAMPTZ DEFAULT NOW()
      );
    `)
    await client.query(`CREATE INDEX IF NOT EXISTS idx_obs_poc ON poc_service.poc_observation(poc_id);`)

    // Issues + corrective actions --------------------------------------------
    await client.query(`
      CREATE TABLE IF NOT EXISTS poc_service.poc_issue (
        id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        display_id        TEXT UNIQUE NOT NULL
                            DEFAULT ('ISS-' || nextval('poc_service.issue_id_seq')),
        account_id        UUID NOT NULL REFERENCES lead_service.accounts(id),
        poc_id            UUID REFERENCES poc_service.poc(id),   -- nullable: may attach to asset later
        title             TEXT NOT NULL,
        description       TEXT,
        severity          TEXT DEFAULT 'medium',     -- low | medium | high | critical
        status            TEXT NOT NULL DEFAULT 'open', -- open | in_progress | resolved | closed
        corrective_action TEXT,
        raised_by         TEXT,
        raised_by_name    TEXT,
        raised_at         TIMESTAMPTZ DEFAULT NOW(),
        resolved_at       TIMESTAMPTZ,
        metadata          JSONB DEFAULT '{}',
        created_at        TIMESTAMPTZ DEFAULT NOW(),
        updated_at        TIMESTAMPTZ DEFAULT NOW()
      );
    `)
    await client.query(`CREATE INDEX IF NOT EXISTS idx_issue_account ON poc_service.poc_issue(account_id, status);`)
    await client.query(`CREATE INDEX IF NOT EXISTS idx_issue_poc     ON poc_service.poc_issue(poc_id);`)

    await client.query('COMMIT')
    console.log('✓ Vault 02: poc_service schema ready')
  } catch (err) {
    await client.query('ROLLBACK')
    console.error('Migration failed:', err)
    throw err
  } finally {
    client.release()
    await pool.end()
  }
}

main().catch((e) => { console.error(e); process.exit(1) })